version: '3.8'

services:
  bot:
    build: .
    container_name: pricewatcher_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GIGACHAT_API_KEY=${GIGACHAT_API_KEY}