version: '3.8'

services:
  bot:
    build: .
    container_name: pricewatcher_bot
    restart: unless-stopped
    shm_size: '1gb'
    mem_limit: 900m          # <-- оставляем 100 МБ для системы
    memswap_limit: 900m      # без свопа
    volumes:
      - ./data:/app/data
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - GIGACHAT_API_KEY=${GIGACHAT_API_KEY}